import Navbar from '@/components/shared/Navbar';

import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Next Auth Dashboard',
  description: 'Generated by create next app',
};

export default function CommonLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="min-h-screen my-2">
      <div>
        <div>
          <Navbar />
        </div>
        <div className="rounded-xl ml-2">{children}</div>
      </div>
    </div>
  );
}
