import Navbar from '@/components/shared/Navbar';
import { authOptions } from '@/utils/authOptions';

import type { Metadata } from 'next';
import { getServerSession } from 'next-auth';

export const metadata: Metadata = {
  title: 'Next Auth Dashboard',
  description: 'Generated by create next app',
};

export default async function CommonLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);
  console.log('session', session);
  return (
    <div className="min-h-screen my-2">
      <div>
        <div>
          <Navbar session={session} />
        </div>
        <div className="rounded-xl ml-2">{children}</div>
      </div>
    </div>
  );
}
